"""service_config content_hash and diff_from

Revision ID: f35b1607cae0
Revises: 0001_init_schema
Create Date: 2026-07-13 15:10:50.579176
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f35b1607cae0"
down_revision: str | None = "0001_init_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content_hash", sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column("diff_from", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_configs", schema=None) as batch_op:
        batch_op.drop_column("diff_from")
        batch_op.drop_column("content_hash")

    # ### end Alembic commands ###
