# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x0eyimai.agent.v1\"\xb7\x01\n\x0c\x41gentMessage\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12.\n\theartbeat\x18\x02 \x01(\x0b\x32\x19.yimai.agent.v1.HeartbeatH\x00\x12/\n\x06status\x18\x03 \x01(\x0b\x32\x1d.yimai.agent.v1.ServiceStatusH\x00\x12)\n\x03\x61\x63k\x18\x04 \x01(\x0b\x32\x1a.yimai.agent.v1.CommandAckH\x00\x42\t\n\x07payload\"\"\n\tHeartbeat\x12\x15\n\ragent_version\x18\x01 \x01(\t\"E\n\rServiceStatus\x12\x13\n\x0bservice_ref\x18\x01 \x01(\t\x12\x0f\n\x07running\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"`\n\nCommandAck\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12%\n\x04kind\x18\x02 \x01(\x0e\x32\x17.yimai.agent.v1.AckKind\x12\n\n\x02ok\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\"\xa9\x01\n\rServerCommand\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x39\n\x06params\x18\x03 \x03(\x0b\x32).yimai.agent.v1.ServerCommand.ParamsEntry\x12\r\n\x05\x66\x65nce\x18\x04 \x01(\x03\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*O\n\x07\x41\x63kKind\x12\x18\n\x14\x41\x43K_KIND_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41\x43K_KIND_RECEIVED\x10\x01\x12\x13\n\x0f\x41\x43K_KIND_RESULT\x10\x02\x32Z\n\x0c\x41gentService\x12J\n\x07\x43onnect\x12\x1c.yimai.agent.v1.AgentMessage\x1a\x1d.yimai.agent.v1.ServerCommand(\x01\x30\x01\x42)Z\'github.com/yimai/axon-agent/gen/agentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/yimai/axon-agent/gen/agentpb'
  _globals['_SERVERCOMMAND_PARAMSENTRY']._loaded_options = None
  _globals['_SERVERCOMMAND_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_ACKKIND']._serialized_start=594
  _globals['_ACKKIND']._serialized_end=673
  _globals['_AGENTMESSAGE']._serialized_start=32
  _globals['_AGENTMESSAGE']._serialized_end=215
  _globals['_HEARTBEAT']._serialized_start=217
  _globals['_HEARTBEAT']._serialized_end=251
  _globals['_SERVICESTATUS']._serialized_start=253
  _globals['_SERVICESTATUS']._serialized_end=322
  _globals['_COMMANDACK']._serialized_start=324
  _globals['_COMMANDACK']._serialized_end=420
  _globals['_SERVERCOMMAND']._serialized_start=423
  _globals['_SERVERCOMMAND']._serialized_end=592
  _globals['_SERVERCOMMAND_PARAMSENTRY']._serialized_start=547
  _globals['_SERVERCOMMAND_PARAMSENTRY']._serialized_end=592
  _globals['_AGENTSERVICE']._serialized_start=675
  _globals['_AGENTSERVICE']._serialized_end=765
# @@protoc_insertion_point(module_scope)
